title = "קמבוצ'ה אהובתי"
baseURL = ""
languageCode = "he"
theme = "ananke"
# Dir = "rtl"
# themesDir = "../.."

DefaultContentLanguage = "he"
SectionPagesMenu = "main"
Paginate = 3 # this is set low for demonstrating with dummy content. Set to a higher number
googleAnalytics = ""
enableRobotsTXT = true

[sitemap]
  changefreq = "monthly"
  priority = 0.5
  filename = "sitemap.xml"

[params]
  favicon = ""
  site_logo = ""
  description = "The last theme you'll ever need. Maybe."
  facebook = ""
  # twitter = "https://twitter.com/GoHugoIO"
  instagram = ""
  youtube = ""
  github = ""
  gitlab = ""
  linkedin = ""
  mastodon = ""
  slack = ""
  stackoverflow = ""
  rss = ""
	body_classes = "heebo"
	post_content_classes = "heebo"
	custom_css = ["css/custom.css"]
  # choose a background color from any on this page: http://tachyons.io/docs/themes/skins/ and preface it with "bg-"
  background_color_class = "bg-black"
  featured_image = "/images/home.jpg"
  recent_posts_number = 2
